### PR TITLE
Add utf-8 characters to tests

### PR DESCRIPTION
**Pull request by mikejritter**
Resolves: #24 

* Adds utf-8 characters to tests which involve reading/writing files

### CODE REVIEW

**Comment by bbranan** [comment]
These are the errors I'm seeing on the Windows Travis build:
```
Running org.duraspace.bagit.BagConfigTest
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.334 sec <<< FAILURE!
testFromFile(org.duraspace.bagit.BagConfigTest)  Time elapsed: 0.333 sec  <<< FAILURE!
org.junit.ComparisonFailure: expected:<"My University [?]"> but was:<"My University [âœ“]">
```
and 
```
Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.078 sec <<< FAILURE!
write(org.duraspace.bagit.BagWriterTest)  Time elapsed: 0.062 sec  <<< FAILURE!
java.lang.AssertionError: 
Expecting:
 <["Bagging-Date: 2020-05-18",
    "Bag-Size: 0 bytes",
    "Payload-Oxum: 1.0",
    "Source-Organization: bagit-support-?"]>
to contain:
 <["Source-Organization: bagit-support-?"]>
but could not find:
 <["Source-Organization: bagit-support-?"]>

	at org.duraspace.bagit.BagWriterTest.write(BagWriterTest.java:148)
```

Running the tests on my local Windows 10 box I see the same 2 errors, though the first one has a slight difference in that the check character shows up properly:
```
org.junit.ComparisonFailure: expected:<"My University [?]"> but was:<"My University [✓]">
```

**Comment by mikejritter** [comment]
Huh, yep seeing those too when building. I wonder if the rebase updated anything, I know the tests were passing before. I'll look into what's going on.

**Comment by mikejritter** [comment]
@bbranan I pushed a commit which should address the issues we saw... at least partially. In any windows terminals (git-bash, powershell, cmd) I'm still seeing a `?` rather than `✓` regardless of any encoding set either through maven with `-Dfile.encoding` or windows with `chcp`.

I'm going to run some tests using the import-export-utility and dspace-replicate to get a feel for what happens when we run it through an actual program.

**Comment by mikejritter** [comment]
Tested with the import-export-utility and saw utf-8 characters written without a problem to the `bag-info.txt`

**Pull request merged**
